"""add report_export_tasks

Revision ID: 4767a93d67a0
Revises: create_drill_tables
Create Date: 2026-09-11 01:55:49.452111+08:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4767a93d67a0'
down_revision: Union[str, None] = 'create_drill_tables'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('report_export_tasks',
        sa.Column('task_no', sa.String(length=50), nullable=False, comment='任务编号'),
        sa.Column('task_type', sa.String(length=50), nullable=False, comment='导出类型'),
        sa.Column('status', sa.String(length=20), nullable=False, comment='状态 pending/running/completed/failed'),
        sa.Column('file_path', sa.String(length=500), nullable=True, comment='文件存储路径'),
        sa.Column('file_name', sa.String(length=200), nullable=True, comment='下载文件名'),
        sa.Column('total_rows', sa.Integer(), nullable=True, comment='总行数'),
        sa.Column('params', sa.JSON(), nullable=True, comment='导出参数'),
        sa.Column('error_message', sa.Text(), nullable=True, comment='失败原因'),
        sa.Column('created_by', sa.Integer(), nullable=False, comment='创建人（DEC-004）'),
        sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True, comment='完成时间'),
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('task_no')
    )
    op.create_index(op.f('ix_report_export_tasks_created_by'), 'report_export_tasks', ['created_by'], unique=False)
    op.create_index(op.f('ix_report_export_tasks_status'), 'report_export_tasks', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_report_export_tasks_status'), table_name='report_export_tasks')
    op.drop_index(op.f('ix_report_export_tasks_created_by'), table_name='report_export_tasks')
    op.drop_table('report_export_tasks')
    # ### end Alembic commands ###
