"""add linkage tables

Revision ID: xxx_linkage_tables
Revises: 54d02fd0cebb
Create Date: 2026-09-10 00:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy import Text
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'xxx_linkage_tables'
down_revision: Union[str, None] = '54d02fd0cebb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Create linkage_plans table
    op.create_table('linkage_plans',
        sa.Column('plan_name', sa.String(length=100), nullable=False),
        sa.Column('org_id', sa.Integer(), nullable=True),
        sa.Column('fire_type', sa.String(length=20), nullable=True),
        sa.Column('trigger_device_type_id', sa.Integer(), nullable=True),
        sa.Column('trigger_alarm_type', sa.String(length=20), nullable=True),
        sa.Column('actions', postgresql.JSONB(astext_type=Text()), nullable=False),
        sa.Column('is_enabled', sa.Boolean(), nullable=False, server_default='true'),
        sa.Column('is_simulation_allowed', sa.Boolean(), nullable=False, server_default='true'),
        sa.Column('created_by', sa.Integer(), nullable=True),
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, server_default=sa.func.now()),
        sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False, server_default=sa.func.now()),
        sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
        sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ),
        sa.ForeignKeyConstraint(['trigger_device_type_id'], ['device_types.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    
    # Create indexes for linkage_plans
    op.create_index('idx_linkage_plans_org', 'linkage_plans', ['org_id'])
    op.create_index('idx_linkage_plans_trigger', 'linkage_plans', ['trigger_device_type_id', 'trigger_alarm_type'])
    op.create_index('idx_linkage_plans_enabled', 'linkage_plans', ['is_enabled'])
    
    # Create alarm_linkage_logs table
    op.create_table('alarm_linkage_logs',
        sa.Column('alarm_id', sa.Integer(), nullable=False),
        sa.Column('plan_id', sa.Integer(), nullable=True),
        sa.Column('action_type', sa.String(length=50), nullable=False),
        sa.Column('target_device_id', sa.Integer(), nullable=True),
        sa.Column('status', sa.String(length=20), nullable=False, server_default='pending'),
        sa.Column('executed_at', sa.DateTime(timezone=True), nullable=True),
        sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
        sa.Column('result_message', Text(), nullable=True),
        sa.Column('is_simulation', sa.Boolean(), nullable=False, server_default='false'),
        sa.Column('delay_seconds', sa.Integer(), nullable=False, server_default='0'),
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, server_default=sa.func.now()),
        sa.ForeignKeyConstraint(['alarm_id'], ['alarms.id'], ),
        sa.ForeignKeyConstraint(['plan_id'], ['linkage_plans.id'], ),
        sa.ForeignKeyConstraint(['target_device_id'], ['devices.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    
    # Create indexes for alarm_linkage_logs
    op.create_index('idx_alarm_linkage_logs_alarm', 'alarm_linkage_logs', ['alarm_id'])
    op.create_index('idx_alarm_linkage_logs_plan', 'alarm_linkage_logs', ['plan_id'])
    op.create_index('idx_alarm_linkage_logs_status', 'alarm_linkage_logs', ['status'])
    op.create_index('idx_alarm_linkage_logs_created', 'alarm_linkage_logs', ['created_at'])
    op.create_index('idx_alarm_linkage_logs_target', 'alarm_linkage_logs', ['target_device_id'])
    
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_alarm_linkage_logs_target', table_name='alarm_linkage_logs')
    op.drop_index('idx_alarm_linkage_logs_created', table_name='alarm_linkage_logs')
    op.drop_index('idx_alarm_linkage_logs_status', table_name='alarm_linkage_logs')
    op.drop_index('idx_alarm_linkage_logs_plan', table_name='alarm_linkage_logs')
    op.drop_index('idx_alarm_linkage_logs_alarm', table_name='alarm_linkage_logs')
    op.drop_table('alarm_linkage_logs')
    op.drop_index('idx_linkage_plans_enabled', table_name='linkage_plans')
    op.drop_index('idx_linkage_plans_trigger', table_name='linkage_plans')
    op.drop_index('idx_linkage_plans_org', table_name='linkage_plans')
    op.drop_table('linkage_plans')
    # ### end Alembic commands ###
